# =============================================================================
# E2E OTel Collector — Makefile
# =============================================================================
# Verification entry points for the CI pipeline. Mirrors the target taxonomy
# used across E2E repos (e.g. terraform-provider-e2e): `make lint` is the
# aggregate; per-component targets (lint-shell, lint-go, helm-lint) feed into it.
#
# This repo currently ships only the build pipeline, installer, and configs.
# The collector Go source (generated by ocb) and the Helm chart land in
# follow-up PRs — so lint-go / helm-lint / helm-validate detect their inputs
# and skip cleanly until those PRs arrive, keeping CI green in the meantime.
# =============================================================================

SHELL := /usr/bin/env bash

GOLANGCI_VERSION ?= v2.6.2

# Shell scripts to lint (skip the generated collector output and .git).
SHELL_FILES := $(shell find . -name '*.sh' -not -path './.git/*' -not -path './collector/dist*' 2>/dev/null)
# Go module roots (none in-tree yet — collector source arrives in a follow-up PR).
GO_MODULE_DIRS := $(shell find . -name go.mod -not -path '*/vendor/*' -not -path './.git/*' 2>/dev/null | xargs -n1 dirname 2>/dev/null)
# Helm chart roots (none in-tree yet — chart arrives in a follow-up PR).
CHART_DIRS := $(shell find . -name Chart.yaml -not -path './.git/*' 2>/dev/null | xargs -n1 dirname 2>/dev/null)

.DEFAULT_GOAL := help

.PHONY: help lint lint-shell lint-go helm-lint helm-validate validate fmt fmtcheck vet install-golangci-lint

help: ## Show all available targets
	@echo "E2E OTel Collector — available targets:"
	@echo ""
	@grep -E '^[a-zA-Z0-9_-]+:.*?## .*$$' $(MAKEFILE_LIST) | \
		awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-22s\033[0m %s\n", $$1, $$2}' | sort

# ── Aggregate ────────────────────────────────────────────────────────────────
lint: lint-shell lint-go helm-lint ## Run all linters (shellcheck → Go → Helm)

validate: helm-validate ## Run all validators (renders + schema-checks Helm manifests)

# ── Shell ────────────────────────────────────────────────────────────────────
lint-shell: ## Lint shell scripts with shellcheck
	@command -v shellcheck >/dev/null 2>&1 || { echo "❌ shellcheck not installed — 'mise use shellcheck' or 'brew install shellcheck'"; exit 1; }
	@if [ -z "$(SHELL_FILES)" ]; then echo "⏭  lint-shell: no shell scripts found — skipping"; exit 0; fi
	@echo "==> shellcheck $(SHELL_FILES)"
	@shellcheck $(SHELL_FILES)
	@echo "✅ shellcheck clean"

# ── Go ───────────────────────────────────────────────────────────────────────
lint-go: ## Lint Go modules (fmt check + vet + golangci-lint); no-op until Go source lands
	@if [ -z "$(GO_MODULE_DIRS)" ]; then \
		echo "⏭  lint-go: no go.mod found — skipping (collector Go source lands in a follow-up PR)"; \
		exit 0; \
	fi; \
	command -v golangci-lint >/dev/null 2>&1 || go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@$(GOLANGCI_VERSION); \
	for dir in $(GO_MODULE_DIRS); do \
		echo "==> Linting Go module: $$dir"; \
		( cd "$$dir" && \
		  unformatted=$$(gofmt -l -s .) && \
		  if [ -n "$$unformatted" ]; then echo "❌ gofmt needed:"; echo "$$unformatted"; exit 1; fi && \
		  go vet ./... && \
		  golangci-lint run ./... ) || exit 1; \
	done; \
	echo "✅ lint-go clean"

fmt: ## Format Go source in place (gofmt -w -s)
	@if [ -z "$(GO_MODULE_DIRS)" ]; then echo "⏭  fmt: no Go source — skipping"; exit 0; fi
	@gofmt -w -s $(GO_MODULE_DIRS)

fmtcheck: ## Check Go formatting without modifying files
	@if [ -z "$(GO_MODULE_DIRS)" ]; then echo "⏭  fmtcheck: no Go source — skipping"; exit 0; fi
	@for dir in $(GO_MODULE_DIRS); do \
		unformatted=$$(gofmt -l -s "$$dir"); \
		if [ -n "$$unformatted" ]; then echo "❌ gofmt needed in $$dir:"; echo "$$unformatted"; exit 1; fi; \
	done; \
	echo "✅ gofmt clean"

vet: ## Run go vet on all modules
	@if [ -z "$(GO_MODULE_DIRS)" ]; then echo "⏭  vet: no Go source — skipping"; exit 0; fi
	@for dir in $(GO_MODULE_DIRS); do echo "==> go vet $$dir"; (cd "$$dir" && go vet ./...) || exit 1; done

install-golangci-lint: ## Install the pinned golangci-lint
	@go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@$(GOLANGCI_VERSION)

# ── Helm ─────────────────────────────────────────────────────────────────────
helm-lint: ## Lint Helm charts (helm lint); no-op until a chart lands
	@if [ -z "$(CHART_DIRS)" ]; then \
		echo "⏭  helm-lint: no Chart.yaml found — skipping (Helm chart lands in a follow-up PR)"; \
		exit 0; \
	fi
	@command -v helm >/dev/null 2>&1 || { echo "❌ helm not installed — 'mise use helm' or 'brew install helm'"; exit 1; }
	@for c in $(CHART_DIRS); do echo "==> helm lint $$c"; helm lint "$$c" || exit 1; done
	@echo "✅ helm-lint clean"

helm-validate: ## Render Helm charts and schema-validate manifests (kubeconform if present)
	@if [ -z "$(CHART_DIRS)" ]; then \
		echo "⏭  helm-validate: no Chart.yaml found — skipping (Helm chart lands in a follow-up PR)"; \
		exit 0; \
	fi
	@command -v helm >/dev/null 2>&1 || { echo "❌ helm not installed — 'mise use helm' or 'brew install helm'"; exit 1; }
	@for c in $(CHART_DIRS); do \
		echo "==> helm template $$c"; \
		if command -v kubeconform >/dev/null 2>&1; then \
			helm template "$$c" | kubeconform -strict -summary -ignore-missing-schemas || exit 1; \
		else \
			helm template "$$c" >/dev/null || exit 1; \
			echo "ℹ️  kubeconform not found — rendered templates only (install kubeconform for schema validation)"; \
		fi; \
	done
	@echo "✅ helm-validate clean"
