# =============================================================================
# E2E OTel Collector — Makefile
# =============================================================================
# Verification entry points for the CI pipeline. Mirrors the target taxonomy
# used across E2E repos (e.g. terraform-provider-e2e): `make lint` is the
# aggregate; per-component targets (lint-shell, lint-go) feed into it.
#
# This repo currently ships only the build pipeline, installer, and configs.
# The collector Go source (generated by ocb, plus any hand-written custom
# components) lands in a follow-up PR — so lint-go detects its input (go.mod)
# and skips cleanly until then, keeping CI green in the meantime.
# =============================================================================

SHELL := /usr/bin/env bash

GOLANGCI_VERSION ?= v2.6.2

# Shell scripts to lint (skip the generated collector output and .git).
SHELL_FILES := $(shell find . -name '*.sh' -not -path './.git/*' -not -path './collector/dist*' 2>/dev/null)
# Go module roots (none in-tree yet — collector source arrives in a follow-up PR).
GO_MODULE_DIRS := $(shell find . -name go.mod -not -path '*/vendor/*' -not -path './.git/*' 2>/dev/null | xargs -n1 dirname 2>/dev/null)

.DEFAULT_GOAL := help

.PHONY: help lint lint-shell lint-go test fmt fmtcheck vet install-golangci-lint changelog

help: ## Show all available targets
	@echo "E2E OTel Collector — available targets:"
	@echo ""
	@grep -E '^[a-zA-Z0-9_-]+:.*?## .*$$' $(MAKEFILE_LIST) | \
		awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-22s\033[0m %s\n", $$1, $$2}' | sort

# ── Aggregate ────────────────────────────────────────────────────────────────
lint: lint-shell lint-go ## Run all linters (shellcheck → Go)

# ── Shell ────────────────────────────────────────────────────────────────────
lint-shell: ## Lint shell scripts with shellcheck
	@command -v shellcheck >/dev/null 2>&1 || { echo "❌ shellcheck not installed — 'mise use shellcheck' or 'brew install shellcheck'"; exit 1; }
	@if [ -z "$(SHELL_FILES)" ]; then echo "⏭  lint-shell: no shell scripts found — skipping"; exit 0; fi
	@echo "==> shellcheck $(SHELL_FILES)"
	@shellcheck $(SHELL_FILES)
	@echo "✅ shellcheck clean"

# ── Test ───────────────────────────────────────────────────────────────────
test: ## Run bats unit tests for install.sh
	@command -v bats >/dev/null 2>&1 || { echo "❌ bats not installed — 'brew install bats-core' or 'apt install bats'"; exit 1; }
	@echo "==> bats tests/"
	@bats tests/
	@echo "✅ bats tests passed"

# ── Go ───────────────────────────────────────────────────────────────────────
lint-go: ## Lint Go modules (fmt check + vet + golangci-lint); no-op until Go source lands
	@if [ -z "$(GO_MODULE_DIRS)" ]; then \
		echo "⏭  lint-go: no go.mod found — skipping (collector Go source lands in a follow-up PR)"; \
		exit 0; \
	fi; \
	command -v golangci-lint >/dev/null 2>&1 || go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@$(GOLANGCI_VERSION); \
	for dir in $(GO_MODULE_DIRS); do \
		echo "==> Linting Go module: $$dir"; \
		( cd "$$dir" && \
		  unformatted=$$(gofmt -l -s .) && \
		  if [ -n "$$unformatted" ]; then echo "❌ gofmt needed:"; echo "$$unformatted"; exit 1; fi && \
		  go vet ./... && \
		  golangci-lint run ./... ) || exit 1; \
	done; \
	echo "✅ lint-go clean"

fmt: ## Format Go source in place (gofmt -w -s)
	@if [ -z "$(GO_MODULE_DIRS)" ]; then echo "⏭  fmt: no Go source — skipping"; exit 0; fi
	@gofmt -w -s $(GO_MODULE_DIRS)

fmtcheck: ## Check Go formatting without modifying files
	@if [ -z "$(GO_MODULE_DIRS)" ]; then echo "⏭  fmtcheck: no Go source — skipping"; exit 0; fi
	@for dir in $(GO_MODULE_DIRS); do \
		unformatted=$$(gofmt -l -s "$$dir"); \
		if [ -n "$$unformatted" ]; then echo "❌ gofmt needed in $$dir:"; echo "$$unformatted"; exit 1; fi; \
	done; \
	echo "✅ gofmt clean"

vet: ## Run go vet on all modules
	@if [ -z "$(GO_MODULE_DIRS)" ]; then echo "⏭  vet: no Go source — skipping"; exit 0; fi
	@for dir in $(GO_MODULE_DIRS); do echo "==> go vet $$dir"; (cd "$$dir" && go vet ./...) || exit 1; done

install-golangci-lint: ## Install the pinned golangci-lint
	@go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@$(GOLANGCI_VERSION)

# ── Changelog ────────────────────────────────────────────────────────────────
changelog: ## Add a CHANGELOG.md entry from git commits — usage: make changelog VERSION=1.2.3
	@if [ -z "$(VERSION)" ]; then echo "❌ VERSION is required. Usage: make changelog VERSION=1.2.3"; exit 1; fi
	@touch CHANGELOG.md
	@DATE=$$(date +%Y-%m-%d); \
	PREV_TAG=$$(git tag --sort=-v:refname | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$$' | grep -Fvx "v$(VERSION)" | head -1); \
	if [ -n "$$PREV_TAG" ]; then \
		COMMITS=$$(git log $$PREV_TAG..HEAD --pretty=format:"- %s" --no-merges 2>/dev/null | grep -v "^- Merge" | head -30); \
	else \
		COMMITS=$$(git log -20 --pretty=format:"- %s" --no-merges 2>/dev/null); \
	fi; \
	[ -z "$$COMMITS" ] && COMMITS="- Version bump"; \
	{ \
		echo "## [$(VERSION)] - $$DATE"; \
		echo ""; \
		echo "$$COMMITS"; \
		echo ""; \
		cat CHANGELOG.md; \
	} > CHANGELOG.md.tmp && mv CHANGELOG.md.tmp CHANGELOG.md; \
	echo "✅ CHANGELOG.md updated for v$(VERSION) — review with 'git diff CHANGELOG.md'"
